### ISSUE TITLE
Error during Sydney 10.4.1 compiling

### ISSUE THREAD

**Issue by shineworld** [Laex/Delphi-OpenCV-Class#12]
Hi Laex,

I've tried to build Delphi-OpenCV-Class with Syndey 10.4.1 following your README info.
When I try to build the package I obtain this error message:

![image](https://user-images.githubusercontent.com/1633598/158807412-de486aa1-1804-414a-b491-b8fc21b1de53.png)

**Comment by Laex** [comment]
Try in the file "Delphi-OpenCV-Class\source\cpp.utils.pas" on line 114 to change
TPtr<T:record> = record
on the
TPtr<T> = record

**Comment by shineworld** [comment]
Perfect now compile :)

Another error during design package compilation:

  dibhdr := @buf;

to 

  dibhdr := pBITMAPINFOHEADER(@buf);


![image](https://user-images.githubusercontent.com/1633598/158866452-b9a24c08-f689-4747-b4c9-b4cee9dd02e2.png)

**Comment by Laex** [comment]
Yes, I corrected that too.
