### ISSUE TITLE
Samples - missing dll

### ISSUE THREAD

**Issue by BennieC** [Laex/Delphi-OpenCV-Class#14]
I have been trying to run the samples but the system complains about a missing dll

The code execution cannot proceed because VCRUNTIME140_1D.dll was not found. Reinstalling the program may fix this problem. 

I have tried various ways, even installing Microsoft Visual Studio but this dll remains missing.  Any suggestions on how to proceed.

**Comment by 13501714030** [comment]
same issue, but you may switch to release mode for running

**Comment by Laex** [comment]
For "release" mode try reinstalling "Visual C++ Redistributable for Visual Studio 2015"
https://www.microsoft.com/en-ca/download/details.aspx?id=48145
or
https://visualstudio.microsoft.com/us/vs/older-downloads/
This will solve the problem with VCRUNTIME140_1.dll

For VCRUNTIME140_1D.dll and "debug" mode, you need to install Visual Studio (version 2022 is also possible) or contact the person who has it installed. I did not find a separate package for installation.
You can also see the discussion in
https://developercommunity.visualstudio.com/t/visual-c-debug-redistributables/220262

**Comment by Laex** [comment]
To disable the use of debug dlls - comment line
{$DEFINE USE_DEBUG_DLLS} // Use debug OpenCV and VisualStudio's DLLs.
in
opt.inc
