### ISSUE TITLE
Samples - unable to run

### ISSUE THREAD

**Issue by BennieC** [Laex/Delphi-OpenCV-Class#15]
I have tried to run any of the samples.  After locating a vcruntime140_1d.dll online and loading it into system32 I get the following error

**videocapture.exe - Application Error
The application was unable to start correctly (0xc000007b). Click OK to close the application.**

I get the same if I run in non-debug mode.  Any idea on how to trace the problem as I see no debug information

**Comment by Laex** [comment]
I have Visual Studio Community Version 17.1 installed (https://visualstudio.microsoft.com/en/free-developer-offers/), which installed debug versions of dynamic libraries, including vcruntime140_1d.dll - size 54192 bytes, version 14.31. 31103.0.
With this library in debug mode, everything starts up fine. 
Perhaps you have vcruntime140_1d.dll installed together with another program - a different version, not the one with which the dlls from OpenCV were compiled.
For installation of debug versions, see the discussion in
https://developercommunity.visualstudio.com/t/visual-c-debug-redistributables/220262

**Comment by Laex** [comment]
To disable the use of debug dlls - comment line
{$DEFINE USE_DEBUG_DLLS} // Use debug OpenCV and VisualStudio's DLLs.
in
opt.inc
