### ISSUE TITLE
Unable to run DEBUG Delphi - follow on from issue #15

### ISSUE THREAD

**Issue by BennieC** [Laex/Delphi-OpenCV-Class#19]
Apologies for not responding sooner but I was dragged away from this project.
I did not find the line that indicates the use of DEBUG_DLLS in opt.inc. I did include it and tried also with UNDEF but still have the same problem. Running in Release mode works but does not help my own debugging needs.

**Comment by Laex** [comment]
The USE_DEBUG_DLLS flag only affects the output of OpenCV diagnostic messages, and then only to the console (if you are not using a console application, then you will not see error messages). It is not possible to enter opencv dll through delphi (only in the form of assembler code).
Or did I not understand the question?
