### ISSUE TITLE
Dynamic path to OpenCVRootPath

### ISSUE THREAD

**Issue by hafedh-trimeche** [Laex/Delphi-OpenCV-Class#3]
Hello,

Would OpenCVRootPath set to a dynamic path (MyLocation\sources) so to not modify the Git/SVN CVResource.pas?

Best regards.

**Comment by Laex** [comment]
Since it is not known where the unpacked OpenCV will be located, it is not known in advance what the path will be.
This path is only needed to run the examples, it is not needed for your own projects.
