### ISSUE TITLE
Can not build on Delphi 11

### ISSUE THREAD

**Issue by jchdng** [Laex/Delphi-OpenCV-Class#33]
The error message: [dcc64 Fatal Error] dclCVClass.dpk(35): E2202 Required package 'designide' not found

**Comment by Laex** [comment]
designide.dcp is part of Delphi, so it should find this file if your Delphi install is clean.
Please locate this file and make sure the folder where designide.dcp is located is in your library path.

**Comment by jchdng** [comment]
64bit "designide.dcp " file is missing, 32bit's is existing but 'opt.inc' can't found.

**Comment by jchdng** [comment]
Should I install radstudio again? I have no idea about the missing files.

**Comment by jchdng** [comment]
64bit does not has "designide.dcp" files ,the IDE is 32 bits

**Comment by Laex** [comment]
dclCVClass is 32 bits

**Comment by jchdng** [comment]
Thanks! Should build with 32bit.
