### ISSUE TITLE
VCRUNTIME140_1D.DLL missing

### ISSUE THREAD

**Issue by fabianosegal** [Laex/Delphi-OpenCV-Class#41]
i´ve tried to find out this library without success.
there are no way to run any sample without this one.

please explain this to us

**Comment by checkdigits** [comment]
You need to update your Windows install to include the Visual C++ runtime.

Follow the instructions here: https://answers.microsoft.com/en-us/windows/forum/all/vcruntime140dll-and-msvcp140dll-missing-in-windows/caf454d1-49f4-4d2b-b74a-c83fb7c38625
