### ISSUE TITLE
TCView Exception

### ISSUE THREAD

**Issue by RadekXxX** [Laex/Delphi-OpenCV-Class#42]
I added a TCView component, loaded the image into TMat and converted to Gray, displayed in TCView raised an exception, displayed using imshow works.

```
unit Unit1;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, CVClass, Vcl.StdCtrls, cpp.utils, cv.resource, cv.opencv;

type
  TForm1 = class(TForm)
    View: TCVView;
    Button1: TButton;
    procedure Button1Click(Sender: TObject);
  private
  public
  end;

var
  Form1: TForm1;

implementation

{$R *.dfm}

procedure TForm1.Button1Click(Sender: TObject);
var
 frameOrig, frameGray: TMat;
begin
  frameOrig := imread ('stuff.jpg', IMREAD_COLOR);
  cvtColor (frameOrig, frameGray, COLOR_BGR2GRAY);
//  imshow ('', frameGray); This OK
  View.DrawMat (frameGray); // Exception
end;

end.
```

**Comment by RadekXxX** [comment]
Thank you, after the repair it no longer reports an exception, but the gray function is displayed correctly only with "imshow", if I display the MAT in TCVView, it has a greenish color.
![Gray](https://github.com/user-attachments/assets/4d8defda-a409-4498-8ab7-5a3b4c6a9f8e)

**Comment by Laex** [comment]
The CVClass.pas module has a function ipDraw, which displays a matrix (TMat). To output black/white images, the palette is filled with Rgb(i, i, i) - this is not correct.
ipDraw requires improvement to take into account the type of images and the bit depth of the color encoding.
