### ISSUE TITLE
Required package 'designide' not found (64 bit)

### ISSUE THREAD

**Issue by GRUhub** [Laex/Delphi-OpenCV-Class#44]
Delphi 10.4.2

**To install components**
For components, install the packages from
_<project>\packages\<Delphi Version>\CVClassGroup.groupproj ..._

Compile Windows 64 bit platform, error: [dcc64 Fatal Error] dclCVClass.dpk(35): E2202 Required package 'designide' not found.
I can't Add Reference ... ' to Requires designide.dcp' - file not found.

if try compile Windows 32bit platform, error: [dcc32 Fatal Error] dclCVClass.dpk(40): F2048 Bad unit format: '..\CVClass.dcu' - Expected version: 34.0, Windows Unicode(x86) Found version: 34.0, Windows Unicode(x64)

**Comment by Laex** [comment]
**The target platform should be installed as shown in the figure.**

![pic](https://github.com/user-attachments/assets/97695838-7637-4034-875c-41ca62be8e14)

**Comment by GRUhub** [comment]
My mistake. After compile error <... Expected version: 34.0, Windows Unicode(x86) Found version: 34.0, Windows Unicode(x64) ...> I renamed bad *.dcu files (cpp.utils,  cv.external, cv.opencv) to *.dcu_ `<project>\source'.

Error:
![image](https://github.com/user-attachments/assets/5fe45f5d-348e-482e-a90a-352785b5c210)

Install **dclCVClass280.bpl**
