### ISSUE TITLE
[dcc32 Error] saturate.impl.inc(28): E2003 Undeclared identifier: 'TValue'

### ISSUE THREAD

**Issue by tata9527** [Laex/Delphi-OpenCV-Class#7]
There was an error while installing the component. I modified the opt.inc file to temporarily resolve the problem.
opt.inc
{$IFDEF RELEASE}
{ }{$DEFINE DELAYED_LOAD_DLL}
{ }{$DEFINE USE_INLINE}
**{ }{$DEFINE USE_TYPEINFO}**
{$ELSE}
**{ }**
{$ENDIF}
//
{$WEAKLINKRTTI ON}
{$RTTI EXPLICIT METHODS([]) PROPERTIES([]) FIELDS([])}
//
{$WARN SYMBOL_PLATFORM OFF}
{$WRITEABLECONST ON}
{$POINTERMATH ON}
{$MINENUMSIZE 4}
{$TYPEDADDRESS ON}

**Comment by Laex** [comment]
Fixed in a609d93571edc6b969f507653ae8b6239607de31
